### ISSUE TITLE
plans for Swift 3.0 and xcode 8

### ISSUE THREAD

**Issue by CrislerAnytimes** [xxxAIRINxxx/ViewPagerController#4]
Hi, 

First of all thanks for the awesome stuff you did. Its very useful. I was wondering if you have any plans on upgrading the codebase to swift 3.0?

Thanks
- Cris

**Comment by xxxAIRINxxx** [comment]
Hi!

Sorry... WIP now. 😭 
please wait.

**Comment by CrislerAnytimes** [comment]
Thanks for the swift reply. ;) 

Hope it will be done soon. :) Will be waiting for it.

**Comment by xxxAIRINxxx** [comment]
@CrislerAnytimes 
finished 😭

**Comment by CrislerAnytimes** [comment]
Awesome! 👍 👍 👍
